#!/bin/bash

if [ "#$1" = "#" ]; then
  echo ""
  echo "cpb - make backup file (XXXXX.yyyy-mm-dd_hh-mm-ss)"
  echo "  usage: cpb <filename/directory>"
  echo ""
  exit 255
fi

cp -pr "$1" "`echo $1 | sed -e \"s|/*$||\"`.`date +%Y-%m-%d_%H-%M-%S`"
exit $RETVAL
